### ISSUE TITLE
How to implement on other networks?

### ISSUE THREAD

**Issue by twshen2000** [selkerdawy/filter-vs-layer-pruning#1]
Hi, 

How to implement on other networks (e.g. mobilenet)? 

Thanks and Regards,
Wai

**Comment by selkerdawy** [comment]
Hi,

To add support for new model:
- Define the model with gates/masks after layers or blocks of interest to calculate the criteria for. Such as in [here](https://github.com/selkerdawy/filter-vs-layer-pruning/blob/master/cifar/resnet56.py#L28)
- Adjust one_shot.sh [script](https://github.com/selkerdawy/filter-vs-layer-pruning/blob/master/one_shot.sh) to calculate the criteria for each pruning candidate. 
- at this stage you can plot the criteria per layer/block pruning candidate as the average of its filters. You can check plot function similar to [here](https://github.com/selkerdawy/filter-vs-layer-pruning/blob/master/plot_layer_importance.py#L79). 
- Finally, you can either manually replace the layer by identity and finetune or create an automatic function like [get_pruned_resnet56](https://github.com/selkerdawy/filter-vs-layer-pruning/blob/master/finetune.py#L65) and finetune. I recommend to start by manually replacing the layer or block so you can adjust any weight shapes if needed as explained in the paper section 4.1.
<p align="center">
<img src="https://user-images.githubusercontent.com/31852162/101931329-7e001580-3b96-11eb-8d98-80a9fb0ef232.png"  width="550">
</p>
I hope you find this helpful and let me know if you have further questions.

**Comment by twshen2000** [comment]
Thank you very much!
